### ISSUE TITLE
Bot does not store message from users without a username

### ISSUE THREAD

**Issue by Hoi15A** [PROGRADE-Tech/Tarchivebot#48] opened 2017-07-17 15:56 UTC
As the title says, somewhere within the logging stuff breaks and does not actually log a message when a user without a username has written the message.
<hr>
<b>Reproduce:</b><br>
Post as user without username

**Comment by fuerbringer** [comment] 2017-07-18 08:23
Going to fix this as soon as possible. Just gonna leave these links for future reference (when I decide to start fixing this issue):

- https://github.com/PROGRADE-Tech/Tarchivebot/blob/master/libs/logger.js#L41
- https://github.com/PROGRADE-Tech/Tarchivebot/blob/master/libs/logger.js#L56

These are likely the cause of this particular issue.

**Comment by fuerbringer** [comment] 2017-07-27 13:54
Was fixed in https://github.com/PROGRADE-Tech/Tarchivebot/commit/8b1b0807e36ca46a4a27d22d323efe7a67b0eb81

**Closed by fuerbringer** 2017-07-27 13:54 UTC
Labels: Backend, Bug
